spring:
  application:
    name: TSAD-Backend-Service
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

server:
  port: 8090

cloud:
  aws:
    credentials:
      access-key: AKIAVRUVUZQGWLN5PORP
      secret-key: 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
    region:
      static: ap-southeast-1

security:
  jwt-token:
    secret: 0yN2Fx1RvLpoNIDdobuUTEBjb9BbMynN

webservicedb:
  datasource:
    poolName: webservicedb-pool
    connectionTimeOut: 10000
    maximumPoolSize: 20
    jdbcUrl: jdbc:postgresql://192.168.1.20:5434/tsad_prod_db
    username: tsad_prod
    password: tsad@prod1124
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org:
      springframework:
        security=DEBUG:

springdoc:
  api-docs:
    path: /tsad/api/v3/api-docs
  swagger-ui:
    path: /tsad/api/swagger-ui.html
    config-url: /tsad/api/v3/api-docs/swagger-config
