spring:
  application:
    name: TSAD-Backend-Service
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

server:
  port: 8090
  servlet:
    context-path: /tsad/api

cloud:
  aws:
    credentials:
      access-key: AKIAVRUVUZQGWLN5PORP
      secret-key: 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
    region:
      static: ap-southeast-1

security:
  jwt-token:
    secret: f7RDrRhuJo6McWeCQlBrY68SnjX8JT8r

webservicedb:
  datasource:
    poolName: webservicedb-pool
    connectionTimeOut: 10000
    maximumPoolSize: 20
    jdbcUrl: jdbc:postgresql://192.168.1.100:5433/tsad_local_db
    username: tsad_local
    password: tsad-24@local
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    url: /tsad/api/v3/api-docs
    config-url: /tsad/api/v3/api-docs/swagger-config
    disable-swagger-default-url: true