spring:
  application:
    name: TSAD-Backend
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

server:
  port: 8080

cloud:
  aws:
    credentials:
      access-key: AKIAVRUVUZQGWLN5PORP
      secret-key: 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
    region:
      static: ap-southeast-1

webservicedb:
  datasource:
    poolName: webservicedb-pool
    connectionTimeOut: 10000
    maximumPoolSize: 20
    jdbcUrl: jdbc:postgresql://192.168.1.20:5432/tsad_local_db
    username: tsad_local
    password: tsad-24@local
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
